name: 🆕 New Ontology Submission
labels:
  - ontology-submission
description: >
  Fill in the fields below to submit a new ontology entry. Your submission
  will be collected for review; it will not directly update the master Excel.
title: "Ontology submission: ${{ github.event.issue.number }}"

body:
  - type: input
    id: name
    attributes:
      label: Name
      description: Name of the ontology
      placeholder: e.g. Modelling and Standards Ontology

  - type: input
    id: acronym
    attributes:
      label: Acronym
      description: Namespace acronym
      placeholder: e.g. MNS

  - type: input
    id: version
    attributes:
      label: Version
      description: Latest released version
      placeholder: e.g. 0.0.v

  - type: input
    id: year
    attributes:
      label: Year published
      description: Year that version was created
      placeholder: e.g. 2024

  - type: textarea
    id: short_description
    attributes:
      label: Short Description
      description: Brief one-sentence summary of the ontology
      placeholder: e.g. Describes modelling and standards used in renovation projects

  - type: input
    id: uri
    attributes:
      label: URI/Namespace
      placeholder: e.g. https://w3id.org/example#

  - type: input
    id: reference
    attributes:
      label: Reference
      description: Web page or DOI that documents the ontology
      placeholder: e.g. https://example.org/paper

  - type: input
    id: linked_aec
    attributes:
      label: Linked-to ontologies AECO
      description: Acronyms of AECO ontologies; use semicolons to separate multiple values
      placeholder: bot; ifc

  - type: input
    id: link_to_upper
    attributes:
      label: Linked-to ontologies UPPER
      description: Acronyms such as schema, skos, prov, etc.; use semicolons to separate
      placeholder: schema; skos

  - type: input
    id: linked_other
    attributes:
      label: Linked other professional domain ontologies
      description: Ontologies outside AECO (e.g. eli); use semicolons to separate
      placeholder: eli
