name: 🆕 New Ontology Submission
description: >
  Fill in the fields below to submit a new ontology entry. Your submission
  will be collected for review; it will not directly update the master Excel.
title: "Ontology submission: ${{ github.event.issue.number }}"
labels:
  - ontology-submission
body:
  - type: input
    id: name
    attributes:
      label: Name
      description: Name of the ontology
      placeholder: e.g. BIMERR Annotation Objects Ontology

  - type: input
    id: acronym
    attributes:
      label: Acronym
      description: Namespace acronym, e.g. ao

  - type: input
    id: uri
    attributes:
      label: URI/Namespace
      description: e.g. https://w3id.org/your-ontology#

  - type: input
    id: reference
    attributes:
      label: Reference
      description: Web link to a webpage or DOI of the paper

  - type: input
    id: linked_aec
    attributes:
      label: Linked AEC ontologies
      description: >
        Acronyms of ontologies (preferably already in BE-OLS). If not,
        please submit an Issue to add those too.

  - type: input
    id: link_to_upper
    attributes:
      label: Link to upper ontologies
      description: >
        Acronyms like schema, terms, prov, skos, vann, cc, foaf, qudt,
        unit, og, fno

  - type: input
    id: linked_other
    attributes:
      label: Linked other professional domain ontologies
      description: >
        Acronyms of ontologies in related domains (e.g. eli)
