name: 🆕 New Ontology Submission
labels:
  - ontology-submission
description: >
  Fill in the fields below to submit a new ontology entry. Your submission
  will be collected for review; it will not directly update the BE-OLS.
title: "Ontology submission: ${{ github.event.issue.number }}"

body:
  - type: input
    id: title
    attributes:
      label: Title
      description: Title/Name of the ontology
      placeholder: e.g. Modelling and Standards Ontology

  - type: input
    id: prefix
    attributes:
      label: Prefix
      description: Namespace prefix
      placeholder: e.g. bot, saref4bldg

  - type: input
    id: version
    attributes:
      label: Version
      description: Latest released version
      placeholder: e.g. 0.0.v

  - type: input
    id: created
    attributes:
      label: Created
      description: Year that version was created
      placeholder: e.g. 2024

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Brief summary of the ontology
      placeholder: e.g. This ontology supports topic/use-case X and serves stakeholder Y, which is useful because Z.

  - type: input
    id: uri
    attributes:
      label: URI
      placeholder: https://w3id.org/MnSOntology#


  - type: input
    id: reference
    attributes:
      label: Reference
      description: Web page or DOI of publication that documents the ontology
      placeholder: e.g. https://ec-3.org/#

  - type: input
    id: linked_aec
    attributes:
      label: Linked-to ontologies AECO
      description: Prefixes of AECO ontologies that the ontology links to. Look-up existing prefixes in BE-OLS. Use semicolons to separate multiple values
      placeholder: bot; ifc

  - type: input
    id: link_upper
    attributes:
      label: Linked-to ontologies UPPER
      description: Prefixes of upper ontologies that the ontology links to. For example: schema, skos, prov, dcterms, foaf, etc.; use semicolons to separate
      placeholder: schema; skos

  - type: input
    id: linked_other
    attributes:
      label: Linked-to ontologies OTHER
      description: Prefixes of ontologies outside AECO that the ontology links to. For example: eli. Use semicolons to separate
      placeholder: eli
