name: 🆕 New Ontology Submission
description: Fill in the fields below to submit a new ontology entry. This will generate a standalone Excel you can review.
title: "Ontology submission: ${{ github.event.issue.number }}"
labels:
  - ontology-submission
body:
  - type: input
    id: name
    attributes:
      label: Name
  - type: input
    id: acronym
    attributes:
      label: Acronym
  - type: input
    id: version
    attributes:
      label: Version
  - type: input
    id: year
    attributes:
      label: Year published
  - type: input
    id: domain
    attributes:
      label: Primary Domain
  # …add one block per column in your sheet…
